name: Comparar Archivos JSON

on:
  push:
    branches:
      - main # Cambia a la rama principal de tu repositorio

jobs:
  comparar-archivos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Ejecutar el Action Personalizado
        id: comparar-json
        uses: ./ # Ruta al directorio donde se encuentra el Action Personalizado
        with:
          ARCHIVO1: example01.json
          ARCHIVO2: example02.json

      - name: Imprimir JSON Resultante
        run: echo "${{ steps.comparar-json.outputs.json_resultante }}"
