name: Compare JSON Files

on:
  push:
    branches:
      - main  # o el nombre de tu rama predeterminada

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compare JSON files
      id: compare-json
      uses: ./  # Esto apunta a la raíz del repositorio donde reside tu action.yml
      with:
        file1: 'example01.json'
        file2: 'example02.json'

    - name: Show comparison result
      run: |
        echo "Comparison result: ${{ steps.compare-json.outputs.result }}"
